
-- Create WAREHOUSES
create WAREHOUSE IF NOT EXISTS IDENTIFIER('"VISUALIZATION"') COMMENT = '' WAREHOUSE_SIZE = 'X-Small' AUTO_RESUME = true AUTO_SUSPEND = 300 ENABLE_QUERY_ACCELERATION = false WAREHOUSE_TYPE = 'STANDARD' MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';
create WAREHOUSE IF NOT EXISTS IDENTIFIER('"INGESTION"') COMMENT = '' WAREHOUSE_SIZE = 'X-Small' AUTO_RESUME = true AUTO_SUSPEND = 300 ENABLE_QUERY_ACCELERATION = false WAREHOUSE_TYPE = 'STANDARD' MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

-- Create Databases
CREATE DATABASE IF NOT EXISTS RAW;
USE RAW;
CREATE SCHEMA IF NOT EXISTS STREAMING_STAGING;


CREATE DATABASE IF NOT EXISTS ANALYTICS;
USE ANALYTICS;
CREATE SCHEMA TRANSFORMATIONS;
CREATE SCHEMA WORKSPACE;
CREATE SCHEMA SEMANTIC;
CREATE SCHEMA CONTROL;




--DROP SCHEMA ANALYTICS.STREAMING_STAGING;









