
-- Create WAREHOUSES
create WAREHOUSE IF NOT EXISTS IDENTIFIER('"VISUALIZATION"') COMMENT = '' WAREHOUSE_SIZE = 'X-Small' AUTO_RESUME = true AUTO_SUSPEND = 300 ENABLE_QUERY_ACCELERATION = false WAREHOUSE_TYPE = 'STANDARD' MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';
create WAREHOUSE IF NOT EXISTS IDENTIFIER('"INGESTION"') COMMENT = '' WAREHOUSE_SIZE = 'X-Small' AUTO_RESUME = true AUTO_SUSPEND = 300 ENABLE_QUERY_ACCELERATION = false WAREHOUSE_TYPE = 'STANDARD' MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

-- Create Databases
-- BRONZE
CREATE DATABASE IF NOT EXISTS BRONZE;
USE BRONZE;
CREATE SCHEMA IF NOT EXISTS RAW_ASSETFLOW;


-- SILVER
CREATE DATABASE IF NOT EXISTS SILVER;
USE SILVER;
CREATE SCHEMA IF NOT EXISTS INVESTMENT_MANAGEMENT;

-- GOLD
CREATE DATABASE IF NOT EXISTS GOLD;
USE GOLD;
CREATE SCHEMA IF NOT EXISTS INVESTMENT_MANAGEMENT;









