-- move from RAW to BRONZE
ALTER TABLE RAW.STAGING_ASSETFLOW.STREAM_ASSETS RENAME TO BRONZE.RAW_ASSETFLOW.STREAM_ASSETS;
ALTER TABLE RAW.STAGING_ASSETFLOW.STREAM_INVESTORS RENAME TO BRONZE.RAW_ASSETFLOW.STREAM_INVESTORS;
ALTER TABLE RAW.STAGING_ASSETFLOW.STREAM_MARKET_DATA RENAME TO BRONZE.RAW_ASSETFLOW.STREAM_MARKET_DATA;
ALTER TABLE RAW.STAGING_ASSETFLOW.STREAM_PORTFOLIOS RENAME TO BRONZE.RAW_ASSETFLOW.STREAM_PORTFOLIOS;
ALTER TABLE RAW.STAGING_ASSETFLOW.STREAM_TRADES RENAME TO BRONZE.RAW_ASSETFLOW.STREAM_TRADES;
ALTER TABLE RAW.STAGING_ASSETFLOW._DLT_LOADS RENAME TO BRONZE.RAW_ASSETFLOW._DLT_LOADS;
ALTER TABLE RAW.STAGING_ASSETFLOW._dlt_pipeline_state RENAME TO BRONZE.RAW_ASSETFLOW._dlt_pipeline_state;
ALTER TABLE RAW.STAGING_ASSETFLOW._dlt_version RENAME TO BRONZE.RAW_ASSETFLOW._dlt_version;


DROP SCHEMA RAW.STAGING_ASSETFLOW;
DROP DATABASE RAW;


-- move from ANALYTICS to SILVER
DROP SCHEMA ANALYTICS.TRANSFORMATIONS;
DROP SCHEMA ANALYTICS.WORKSPACE;
DROP SCHEMA ANALYTICS.CONTROL;

-- Transfer Tables
ALTER TABLE ANALYTICS.SEMANTIC.ASSET RENAME TO SILVER.INVESTMENT_MANAGEMENT.ASSET;
ALTER TABLE ANALYTICS.SEMANTIC.AUM RENAME TO SILVER.INVESTMENT_MANAGEMENT.AUM;
ALTER TABLE ANALYTICS.SEMANTIC.DAILY_RETURNS RENAME TO SILVER.INVESTMENT_MANAGEMENT.DAILY_RETURNS;
ALTER TABLE ANALYTICS.SEMANTIC.INVESTOR RENAME TO SILVER.INVESTMENT_MANAGEMENT.INVESTOR;
ALTER TABLE ANALYTICS.SEMANTIC.MARKET_DATA RENAME TO SILVER.INVESTMENT_MANAGEMENT.MARKET_DATA;
ALTER TABLE ANALYTICS.SEMANTIC.PORTFOLIO RENAME TO SILVER.INVESTMENT_MANAGEMENT.PORTFOLIO;
ALTER TABLE ANALYTICS.SEMANTIC.POSITIONS RENAME TO SILVER.INVESTMENT_MANAGEMENT.POSITIONS;
ALTER TABLE ANALYTICS.SEMANTIC.TRADES RENAME TO SILVER.INVESTMENT_MANAGEMENT.TRADES;


DROP DATABASE ANALYTICS;